# Generated by Django 5.0.3 on 2024-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='destination_type',
            field=models.CharField(choices=[('', 'All'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('forest', 'Forest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('difficult', 'Difficult'), ('challenging', 'Challenging'), ('medium', 'Medium')], max_length=50),
        ),
    ]
