# Generated by Django 5.0.3 on 2024-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
