# Generated by Django 5.0.3 on 2024-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_destination_type_alter_place_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='destination_type',
            field=models.CharField(choices=[('', 'All'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('forest', 'Forest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('difficult', 'Difficult'), ('challenging', 'Challenging'), ('medium', 'Medium')], max_length=50),
        ),
    ]
