# Generated by Django 5.0.3 on 2024-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_typology_place_typologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
