# Generated by Django 5.0.3 on 2024-07-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_place_difficulty_place_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('difficult', 'Difficult'), ('challenging', 'Challenging'), ('medium', 'Medium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='duration',
            field=models.CharField(blank=True, choices=[('5 days', '5 days'), ('10 days', '10 days'), ('15 days', '15 days'), ('1 week', '1 week')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
